version: '3'
services:


  phone-book-app-mysql:
    container_name: phone-book-app-mysql
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_URL: jdbc:mysql://phone-book-app-mysql:3306/phone_book_app?autoReconnect=true&useSSL=false
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_leave_tracking
    volumes:
      - ./mysql:/var/lib/phone-book-app-mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

  phone-book-app-redis:
    container_name: phone-book-app-redis
    image: redis:6.2-alpine
    restart: always
    volumes:
      - ./mysql:/var/lib/phone-book-app-redis
    ports:
      - '6379:6379'
    expose:
      - 6379

# docker build -t user_leave_tracking_app -f Dockerfile .
# docker ps
# docker images -a
# docker network ls
# docker run --name user_leave_tracking_app -p 8080:8080 user_leave_tracking_app
# docker image rm user_leave_tracking_app
# docker rmi $(docker images -a -q)

# docker-compose up -d